# Generated by Django 5.0.6 on 2024-05-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_servicedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('headImg', models.ImageField(upload_to='headimg')),
                ('headContent', models.TextField(max_length=500)),
            ],
        ),
    ]
