# Generated by Django 5.0.6 on 2024-05-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_homeinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeinfo',
            name='headContent',
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='headContent1',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='headContent2',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='headContent3',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='headContent4',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='head',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='headImg',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
