# Generated by Django 5.0.6 on 2024-05-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_remove_homeinfo_headcontent_homeinfo_headcontent1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='headContent1',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='headContent2',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='headContent3',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='headContent4',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
