# Generated by Django 5.0.6 on 2024-05-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_alter_homeinfo_headcontent1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeslider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100, null=True)),
                ('headImg', models.ImageField(upload_to='images/')),
                ('header', models.ImageField(null=True, upload_to='')),
                ('city', models.CharField(max_length=100, null=True)),
                ('paragraph', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
