# Generated by Django 5.0.6 on 2024-05-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_homeslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='header',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
