# Generated by Django 5.0.6 on 2024-05-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_homelatestnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeclients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headImg1', models.ImageField(upload_to='images/')),
                ('headImg2', models.ImageField(upload_to='images/')),
                ('headImg3', models.ImageField(upload_to='images/')),
                ('headImg4', models.ImageField(upload_to='images/')),
                ('headImg5', models.ImageField(upload_to='images/')),
                ('headImg6', models.ImageField(upload_to='images/')),
                ('headImg7', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
