# Generated by Django 5.0.6 on 2024-05-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_homeclients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeclients',
            name='headImg7',
        ),
    ]
