# Generated by Django 5.0.6 on 2024-05-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_aboutcreativeteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicetextplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header1', models.CharField(max_length=200)),
                ('textplan', models.TextField()),
            ],
        ),
    ]
