# Generated by Django 5.0.6 on 2024-05-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_servicetextplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicepricingplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=100)),
                ('text2', models.CharField(max_length=100)),
                ('text3', models.CharField(max_length=100)),
                ('text4', models.CharField(max_length=100)),
                ('text5', models.CharField(max_length=100)),
                ('text6', models.CharField(max_length=100)),
                ('text7', models.CharField(max_length=100)),
            ],
        ),
    ]
