# Generated by Django 5.0.6 on 2024-05-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0015_portphotogallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='portvideogallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryvideosImg', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
