# Generated by Django 5.0.6 on 2024-05-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0016_portvideogallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelatestnews',
            name='date',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
