# Generated by Django 5.0.6 on 2024-05-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0017_alter_homelatestnews_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='portvideogallery',
            name='stylesheet',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
