# Generated by Django 5.0.6 on 2024-05-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0018_portvideogallery_stylesheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portvideogallery',
            old_name='stylesheet',
            new_name='column1',
        ),
        migrations.AddField(
            model_name='portvideogallery',
            name='column2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
