# Generated by Django 5.0.6 on 2024-05-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0019_rename_stylesheet_portvideogallery_column1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='portdemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallerydemo', models.ImageField(upload_to='images/')),
                ('col1', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
