# Generated by Django 5.0.6 on 2024-05-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0020_portdemo'),
    ]

    operations = [
        migrations.CreateModel(
            name='portdemo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallerydemo1', models.ImageField(upload_to='images/')),
                ('col', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
