# Generated by Django 5.0.6 on 2024-06-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0026_commentform_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentform',
            name='date',
        ),
    ]
