# Generated by Django 5.0.6 on 2024-06-24 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0027_remove_commentform_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentform',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
