# Generated by Django 5.0.6 on 2024-07-07 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0029_ceremonybook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceremonybook',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
