# Generated by Django 5.0.6 on 2024-07-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0030_alter_ceremonybook_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceremonybook',
            name='contact',
        ),
        migrations.AddField(
            model_name='ceremonybook',
            name='number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
