# Generated by Django 5.0.6 on 2024-07-08 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0031_remove_ceremonybook_contact_ceremonybook_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('packageText1', models.CharField(max_length=100, null=True)),
                ('packageText2', models.CharField(max_length=100, null=True)),
                ('packageText3', models.CharField(max_length=100, null=True)),
                ('packageText4', models.CharField(max_length=100, null=True)),
                ('packageText5', models.CharField(max_length=100, null=True)),
                ('packageText6', models.CharField(max_length=100, null=True)),
                ('packageText7', models.CharField(max_length=100, null=True)),
                ('img1', models.ImageField(upload_to='images/')),
                ('img2', models.ImageField(upload_to='images/')),
                ('img3', models.ImageField(upload_to='images/')),
                ('img4', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='ceremonybook',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
