# Generated by Django 5.0.6 on 2024-07-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0032_items_details_alter_ceremonybook_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_details',
            name='img',
            field=models.ImageField(default=52, upload_to='images/'),
            preserve_default=False,
        ),
    ]
