# Generated by Django 4.2.11 on 2024-07-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0034_rename_date_ceremonybook_fromdate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("number", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("order_id", models.CharField(blank=True, max_length=100)),
                ("paid", models.BooleanField(default=False)),
                ("razorpay_payment_id", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
