# Generated by Django 5.0.6 on 2024-07-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0035_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
