# Generated by Django 5.0.6 on 2024-07-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0039_remove_booking_total_price_booking_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='total_amount',
            new_name='totalamount',
        ),
    ]
