# Generated by Django 5.0.6 on 2024-07-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0040_rename_total_amount_booking_totalamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcreativeteam',
            name='teamsImg',
        ),
        migrations.AddField(
            model_name='aboutcreativeteam',
            name='teamsvideo',
            field=models.FileField(default=12, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
