# Generated by Django 5.0.6 on 2024-07-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0041_remove_aboutcreativeteam_teamsimg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='portdemo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(default='', max_length=100, null=True)),
                ('gallerydemo1', models.ImageField(upload_to='images/')),
                ('col', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
